//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbstockpointEntities : DbContext
    {
        public dbstockpointEntities()
            : base("name=dbstockpointEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tblCampo> tblCampo { get; set; }
        public DbSet<tblCatalogo> tblCatalogo { get; set; }
        public DbSet<tblCompra> tblCompra { get; set; }
        public DbSet<tblDetalleVenta> tblDetalleVenta { get; set; }
        public DbSet<tblPantalla> tblPantalla { get; set; }
        public DbSet<tblPermisoPorPantalla> tblPermisoPorPantalla { get; set; }
        public DbSet<tblProducto> tblProducto { get; set; }
        public DbSet<tblProveedor> tblProveedor { get; set; }
        public DbSet<tblResultado> tblResultado { get; set; }
        public DbSet<tblTokenRecuperar> tblTokenRecuperar { get; set; }
        public DbSet<tblUsuario> tblUsuario { get; set; }
        public DbSet<tblVenta> tblVenta { get; set; }
        public DbSet<tblVentas> tblVentas { get; set; }
        public DbSet<systables> systables { get; set; }
        public DbSet<vwCampo> vwCampo { get; set; }
        public DbSet<vwDetalleVenta> vwDetalleVenta { get; set; }
        public DbSet<vwPantallaPorPermiso> vwPantallaPorPermiso { get; set; }
        public DbSet<vwPantallas> vwPantallas { get; set; }
        public DbSet<vwProducto> vwProducto { get; set; }
        public DbSet<vwProveedor> vwProveedor { get; set; }
        public DbSet<vwResultado> vwResultado { get; set; }
        public DbSet<vwTablas> vwTablas { get; set; }
        public DbSet<vwtblCompraDetallada> vwtblCompraDetallada { get; set; }
        public DbSet<vwtblTokenRecuperar> vwtblTokenRecuperar { get; set; }
        public DbSet<vwUsuario> vwUsuario { get; set; }
        public DbSet<vwUsuarioLogin> vwUsuarioLogin { get; set; }
        public DbSet<vwVenta> vwVenta { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_ProcesarDiccionario_Result> sp_ProcesarDiccionario(string input)
        {
            var inputParameter = input != null ?
                new ObjectParameter("Input", input) :
                new ObjectParameter("Input", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ProcesarDiccionario_Result>("sp_ProcesarDiccionario", inputParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<uspCampo_Result> uspCampo(Nullable<int> idCampo, string nombreDeTabla, string campoV, string tipoV, string etiquetaV, Nullable<int> longitudV, string descripcionV, string validacionV, Nullable<int> ordenV, string claseV, string catalogoV, Nullable<int> esNuloV, Nullable<int> no_ColumnaV)
        {
            var idCampoParameter = idCampo.HasValue ?
                new ObjectParameter("IdCampo", idCampo) :
                new ObjectParameter("IdCampo", typeof(int));
    
            var nombreDeTablaParameter = nombreDeTabla != null ?
                new ObjectParameter("NombreDeTabla", nombreDeTabla) :
                new ObjectParameter("NombreDeTabla", typeof(string));
    
            var campoVParameter = campoV != null ?
                new ObjectParameter("CampoV", campoV) :
                new ObjectParameter("CampoV", typeof(string));
    
            var tipoVParameter = tipoV != null ?
                new ObjectParameter("TipoV", tipoV) :
                new ObjectParameter("TipoV", typeof(string));
    
            var etiquetaVParameter = etiquetaV != null ?
                new ObjectParameter("EtiquetaV", etiquetaV) :
                new ObjectParameter("EtiquetaV", typeof(string));
    
            var longitudVParameter = longitudV.HasValue ?
                new ObjectParameter("LongitudV", longitudV) :
                new ObjectParameter("LongitudV", typeof(int));
    
            var descripcionVParameter = descripcionV != null ?
                new ObjectParameter("DescripcionV", descripcionV) :
                new ObjectParameter("DescripcionV", typeof(string));
    
            var validacionVParameter = validacionV != null ?
                new ObjectParameter("ValidacionV", validacionV) :
                new ObjectParameter("ValidacionV", typeof(string));
    
            var ordenVParameter = ordenV.HasValue ?
                new ObjectParameter("OrdenV", ordenV) :
                new ObjectParameter("OrdenV", typeof(int));
    
            var claseVParameter = claseV != null ?
                new ObjectParameter("ClaseV", claseV) :
                new ObjectParameter("ClaseV", typeof(string));
    
            var catalogoVParameter = catalogoV != null ?
                new ObjectParameter("CatalogoV", catalogoV) :
                new ObjectParameter("CatalogoV", typeof(string));
    
            var esNuloVParameter = esNuloV.HasValue ?
                new ObjectParameter("EsNuloV", esNuloV) :
                new ObjectParameter("EsNuloV", typeof(int));
    
            var no_ColumnaVParameter = no_ColumnaV.HasValue ?
                new ObjectParameter("No_ColumnaV", no_ColumnaV) :
                new ObjectParameter("No_ColumnaV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspCampo_Result>("uspCampo", idCampoParameter, nombreDeTablaParameter, campoVParameter, tipoVParameter, etiquetaVParameter, longitudVParameter, descripcionVParameter, validacionVParameter, ordenVParameter, claseVParameter, catalogoVParameter, esNuloVParameter, no_ColumnaVParameter);
        }
    
        public virtual ObjectResult<uspCatalogo_Result> uspCatalogo(Nullable<int> id_Catalogo, Nullable<int> idOrigen, string catalogo, string valor, Nullable<int> orden, Nullable<int> valorDefault, string descripcion)
        {
            var id_CatalogoParameter = id_Catalogo.HasValue ?
                new ObjectParameter("Id_Catalogo", id_Catalogo) :
                new ObjectParameter("Id_Catalogo", typeof(int));
    
            var idOrigenParameter = idOrigen.HasValue ?
                new ObjectParameter("IdOrigen", idOrigen) :
                new ObjectParameter("IdOrigen", typeof(int));
    
            var catalogoParameter = catalogo != null ?
                new ObjectParameter("Catalogo", catalogo) :
                new ObjectParameter("Catalogo", typeof(string));
    
            var valorParameter = valor != null ?
                new ObjectParameter("Valor", valor) :
                new ObjectParameter("Valor", typeof(string));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("Orden", orden) :
                new ObjectParameter("Orden", typeof(int));
    
            var valorDefaultParameter = valorDefault.HasValue ?
                new ObjectParameter("ValorDefault", valorDefault) :
                new ObjectParameter("ValorDefault", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspCatalogo_Result>("uspCatalogo", id_CatalogoParameter, idOrigenParameter, catalogoParameter, valorParameter, ordenParameter, valorDefaultParameter, descripcionParameter);
        }
    
        public virtual int uspDelProducto(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDelProducto", idProductoParameter);
        }
    
        public virtual int uspDelTokenRecuperacion(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDelTokenRecuperacion", idUsuarioParameter);
        }
    
        public virtual int uspDelVenta(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDelVenta", idParameter);
        }
    
        public virtual int uspDetalleVenta(Nullable<int> idVenta, Nullable<int> idProducto, Nullable<double> cantidad, Nullable<double> importe)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(double));
    
            var importeParameter = importe.HasValue ?
                new ObjectParameter("Importe", importe) :
                new ObjectParameter("Importe", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDetalleVenta", idVentaParameter, idProductoParameter, cantidadParameter, importeParameter);
        }
    
        public virtual ObjectResult<uspGenerarAleatorio_Result> uspGenerarAleatorio(string correoV, string moduloV, string metodosV, Nullable<int> idEstatusV, string mensajeV, string mensajeDeSistemaV, Nullable<System.DateTime> fechaV)
        {
            var correoVParameter = correoV != null ?
                new ObjectParameter("CorreoV", correoV) :
                new ObjectParameter("CorreoV", typeof(string));
    
            var moduloVParameter = moduloV != null ?
                new ObjectParameter("moduloV", moduloV) :
                new ObjectParameter("moduloV", typeof(string));
    
            var metodosVParameter = metodosV != null ?
                new ObjectParameter("metodosV", metodosV) :
                new ObjectParameter("metodosV", typeof(string));
    
            var idEstatusVParameter = idEstatusV.HasValue ?
                new ObjectParameter("idEstatusV", idEstatusV) :
                new ObjectParameter("idEstatusV", typeof(int));
    
            var mensajeVParameter = mensajeV != null ?
                new ObjectParameter("mensajeV", mensajeV) :
                new ObjectParameter("mensajeV", typeof(string));
    
            var mensajeDeSistemaVParameter = mensajeDeSistemaV != null ?
                new ObjectParameter("mensajeDeSistemaV", mensajeDeSistemaV) :
                new ObjectParameter("mensajeDeSistemaV", typeof(string));
    
            var fechaVParameter = fechaV.HasValue ?
                new ObjectParameter("fechaV", fechaV) :
                new ObjectParameter("fechaV", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGenerarAleatorio_Result>("uspGenerarAleatorio", correoVParameter, moduloVParameter, metodosVParameter, idEstatusVParameter, mensajeVParameter, mensajeDeSistemaVParameter, fechaVParameter);
        }
    
        public virtual ObjectResult<uspGetAccesar_Result> uspGetAccesar(string correoElectronicoV, string claveAccesoV)
        {
            var correoElectronicoVParameter = correoElectronicoV != null ?
                new ObjectParameter("CorreoElectronicoV", correoElectronicoV) :
                new ObjectParameter("CorreoElectronicoV", typeof(string));
    
            var claveAccesoVParameter = claveAccesoV != null ?
                new ObjectParameter("ClaveAccesoV", claveAccesoV) :
                new ObjectParameter("ClaveAccesoV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetAccesar_Result>("uspGetAccesar", correoElectronicoVParameter, claveAccesoVParameter);
        }
    
        public virtual ObjectResult<string> uspGetCSharp(string tabla, string caso)
        {
            var tablaParameter = tabla != null ?
                new ObjectParameter("tabla", tabla) :
                new ObjectParameter("tabla", typeof(string));
    
            var casoParameter = caso != null ?
                new ObjectParameter("caso", caso) :
                new ObjectParameter("caso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspGetCSharp", tablaParameter, casoParameter);
        }
    
        public virtual ObjectResult<uspGetElementosCatalogo_Result> uspGetElementosCatalogo(string catalogo, string idOrigen, string valorDefault)
        {
            var catalogoParameter = catalogo != null ?
                new ObjectParameter("Catalogo", catalogo) :
                new ObjectParameter("Catalogo", typeof(string));
    
            var idOrigenParameter = idOrigen != null ?
                new ObjectParameter("idOrigen", idOrigen) :
                new ObjectParameter("idOrigen", typeof(string));
    
            var valorDefaultParameter = valorDefault != null ?
                new ObjectParameter("ValorDefault", valorDefault) :
                new ObjectParameter("ValorDefault", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetElementosCatalogo_Result>("uspGetElementosCatalogo", catalogoParameter, idOrigenParameter, valorDefaultParameter);
        }
    
        public virtual ObjectResult<uspGetElementosResultados_Result> uspGetElementosResultados(string modulo, string metodos, Nullable<System.DateTime> fecha, Nullable<int> idUsuario)
        {
            var moduloParameter = modulo != null ?
                new ObjectParameter("modulo", modulo) :
                new ObjectParameter("modulo", typeof(string));
    
            var metodosParameter = metodos != null ?
                new ObjectParameter("metodos", metodos) :
                new ObjectParameter("metodos", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetElementosResultados_Result>("uspGetElementosResultados", moduloParameter, metodosParameter, fechaParameter, idUsuarioParameter);
        }
    
        public virtual int uspGetElementosResultadosN(string resultado, string idOrigen, string valorDefault)
        {
            var resultadoParameter = resultado != null ?
                new ObjectParameter("Resultado", resultado) :
                new ObjectParameter("Resultado", typeof(string));
    
            var idOrigenParameter = idOrigen != null ?
                new ObjectParameter("idOrigen", idOrigen) :
                new ObjectParameter("idOrigen", typeof(string));
    
            var valorDefaultParameter = valorDefault != null ?
                new ObjectParameter("ValorDefault", valorDefault) :
                new ObjectParameter("ValorDefault", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGetElementosResultadosN", resultadoParameter, idOrigenParameter, valorDefaultParameter);
        }
    
        public virtual ObjectResult<uspGetJs_Result> uspGetJs(string tabla)
        {
            var tablaParameter = tabla != null ?
                new ObjectParameter("tabla", tabla) :
                new ObjectParameter("tabla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetJs_Result>("uspGetJs", tablaParameter);
        }
    
        public virtual ObjectResult<uspGetPantallaByToken_Result> uspGetPantallaByToken(string token, Nullable<int> idOrigen)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var idOrigenParameter = idOrigen.HasValue ?
                new ObjectParameter("idOrigen", idOrigen) :
                new ObjectParameter("idOrigen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetPantallaByToken_Result>("uspGetPantallaByToken", tokenParameter, idOrigenParameter);
        }
    
        public virtual ObjectResult<uspGetPantallaCheck_Result> uspGetPantallaCheck(Nullable<int> idPantalla)
        {
            var idPantallaParameter = idPantalla.HasValue ?
                new ObjectParameter("IdPantalla", idPantalla) :
                new ObjectParameter("IdPantalla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetPantallaCheck_Result>("uspGetPantallaCheck", idPantallaParameter);
        }
    
        public virtual int uspGetResultados(string resultado, string idOrgen, string valorDefault)
        {
            var resultadoParameter = resultado != null ?
                new ObjectParameter("Resultado", resultado) :
                new ObjectParameter("Resultado", typeof(string));
    
            var idOrgenParameter = idOrgen != null ?
                new ObjectParameter("idOrgen", idOrgen) :
                new ObjectParameter("idOrgen", typeof(string));
    
            var valorDefaultParameter = valorDefault != null ?
                new ObjectParameter("ValorDefault", valorDefault) :
                new ObjectParameter("ValorDefault", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGetResultados", resultadoParameter, idOrgenParameter, valorDefaultParameter);
        }
    
        public virtual int uspGetRnew(string resultado)
        {
            var resultadoParameter = resultado != null ?
                new ObjectParameter("Resultado", resultado) :
                new ObjectParameter("Resultado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGetRnew", resultadoParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> uspGetUsuarioTokenRecuperacion(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("uspGetUsuarioTokenRecuperacion", tokenParameter);
        }
    
        public virtual ObjectResult<uspPantalla_Result> uspPantalla(Nullable<int> idOrigenV, Nullable<int> ordenV, string pantallaV, string urlV, string claseV, string toolTipV, string descripcionV, Nullable<int> idEstatusV, string msgGuardarV, string msgEliminarV, string preguntaEliminarV, string urlMovil)
        {
            var idOrigenVParameter = idOrigenV.HasValue ?
                new ObjectParameter("idOrigenV", idOrigenV) :
                new ObjectParameter("idOrigenV", typeof(int));
    
            var ordenVParameter = ordenV.HasValue ?
                new ObjectParameter("OrdenV", ordenV) :
                new ObjectParameter("OrdenV", typeof(int));
    
            var pantallaVParameter = pantallaV != null ?
                new ObjectParameter("PantallaV", pantallaV) :
                new ObjectParameter("PantallaV", typeof(string));
    
            var urlVParameter = urlV != null ?
                new ObjectParameter("urlV", urlV) :
                new ObjectParameter("urlV", typeof(string));
    
            var claseVParameter = claseV != null ?
                new ObjectParameter("ClaseV", claseV) :
                new ObjectParameter("ClaseV", typeof(string));
    
            var toolTipVParameter = toolTipV != null ?
                new ObjectParameter("ToolTipV", toolTipV) :
                new ObjectParameter("ToolTipV", typeof(string));
    
            var descripcionVParameter = descripcionV != null ?
                new ObjectParameter("DescripcionV", descripcionV) :
                new ObjectParameter("DescripcionV", typeof(string));
    
            var idEstatusVParameter = idEstatusV.HasValue ?
                new ObjectParameter("idEstatusV", idEstatusV) :
                new ObjectParameter("idEstatusV", typeof(int));
    
            var msgGuardarVParameter = msgGuardarV != null ?
                new ObjectParameter("MsgGuardarV", msgGuardarV) :
                new ObjectParameter("MsgGuardarV", typeof(string));
    
            var msgEliminarVParameter = msgEliminarV != null ?
                new ObjectParameter("MsgEliminarV", msgEliminarV) :
                new ObjectParameter("MsgEliminarV", typeof(string));
    
            var preguntaEliminarVParameter = preguntaEliminarV != null ?
                new ObjectParameter("PreguntaEliminarV", preguntaEliminarV) :
                new ObjectParameter("PreguntaEliminarV", typeof(string));
    
            var urlMovilParameter = urlMovil != null ?
                new ObjectParameter("UrlMovil", urlMovil) :
                new ObjectParameter("UrlMovil", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspPantalla_Result>("uspPantalla", idOrigenVParameter, ordenVParameter, pantallaVParameter, urlVParameter, claseVParameter, toolTipVParameter, descripcionVParameter, idEstatusVParameter, msgGuardarVParameter, msgEliminarVParameter, preguntaEliminarVParameter, urlMovilParameter);
        }
    
        public virtual ObjectResult<uspPermisoPorPantalla_Result> uspPermisoPorPantalla(Nullable<int> idPantalla, Nullable<int> idPermiso, Nullable<int> estatus)
        {
            var idPantallaParameter = idPantalla.HasValue ?
                new ObjectParameter("idPantalla", idPantalla) :
                new ObjectParameter("idPantalla", typeof(int));
    
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(int));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspPermisoPorPantalla_Result>("uspPermisoPorPantalla", idPantallaParameter, idPermisoParameter, estatusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> uspPermisoToken(string pantalla, string token)
        {
            var pantallaParameter = pantalla != null ?
                new ObjectParameter("Pantalla", pantalla) :
                new ObjectParameter("Pantalla", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("uspPermisoToken", pantallaParameter, tokenParameter);
        }
    
        public virtual int uspProducto(string descripcion, Nullable<int> idProducto, Nullable<int> piezasXcaja, Nullable<int> idUnidad, Nullable<int> piezasXPaquete, Nullable<int> cantidadMinima, Nullable<int> existencia, Nullable<int> idCategoria, Nullable<double> costoXCaja, Nullable<double> precioPublico, string productos, string codigo, string imagen, Nullable<int> idEstatus)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var piezasXcajaParameter = piezasXcaja.HasValue ?
                new ObjectParameter("PiezasXcaja", piezasXcaja) :
                new ObjectParameter("PiezasXcaja", typeof(int));
    
            var idUnidadParameter = idUnidad.HasValue ?
                new ObjectParameter("idUnidad", idUnidad) :
                new ObjectParameter("idUnidad", typeof(int));
    
            var piezasXPaqueteParameter = piezasXPaquete.HasValue ?
                new ObjectParameter("PiezasXPaquete", piezasXPaquete) :
                new ObjectParameter("PiezasXPaquete", typeof(int));
    
            var cantidadMinimaParameter = cantidadMinima.HasValue ?
                new ObjectParameter("CantidadMinima", cantidadMinima) :
                new ObjectParameter("CantidadMinima", typeof(int));
    
            var existenciaParameter = existencia.HasValue ?
                new ObjectParameter("Existencia", existencia) :
                new ObjectParameter("Existencia", typeof(int));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            var costoXCajaParameter = costoXCaja.HasValue ?
                new ObjectParameter("CostoXCaja", costoXCaja) :
                new ObjectParameter("CostoXCaja", typeof(double));
    
            var precioPublicoParameter = precioPublico.HasValue ?
                new ObjectParameter("PrecioPublico", precioPublico) :
                new ObjectParameter("PrecioPublico", typeof(double));
    
            var productosParameter = productos != null ?
                new ObjectParameter("Productos", productos) :
                new ObjectParameter("Productos", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("idEstatus", idEstatus) :
                new ObjectParameter("idEstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspProducto", descripcionParameter, idProductoParameter, piezasXcajaParameter, idUnidadParameter, piezasXPaqueteParameter, cantidadMinimaParameter, existenciaParameter, idCategoriaParameter, costoXCajaParameter, precioPublicoParameter, productosParameter, codigoParameter, imagenParameter, idEstatusParameter);
        }
    
        public virtual int uspProveedor(string razonSocialV, string direccionV, string contactoV, Nullable<decimal> telefonoContactoV, string correoElectronicoV, Nullable<int> idEmpresaV)
        {
            var razonSocialVParameter = razonSocialV != null ?
                new ObjectParameter("razonSocialV", razonSocialV) :
                new ObjectParameter("razonSocialV", typeof(string));
    
            var direccionVParameter = direccionV != null ?
                new ObjectParameter("direccionV", direccionV) :
                new ObjectParameter("direccionV", typeof(string));
    
            var contactoVParameter = contactoV != null ?
                new ObjectParameter("contactoV", contactoV) :
                new ObjectParameter("contactoV", typeof(string));
    
            var telefonoContactoVParameter = telefonoContactoV.HasValue ?
                new ObjectParameter("telefonoContactoV", telefonoContactoV) :
                new ObjectParameter("telefonoContactoV", typeof(decimal));
    
            var correoElectronicoVParameter = correoElectronicoV != null ?
                new ObjectParameter("correoElectronicoV", correoElectronicoV) :
                new ObjectParameter("correoElectronicoV", typeof(string));
    
            var idEmpresaVParameter = idEmpresaV.HasValue ?
                new ObjectParameter("idEmpresaV", idEmpresaV) :
                new ObjectParameter("idEmpresaV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspProveedor", razonSocialVParameter, direccionVParameter, contactoVParameter, telefonoContactoVParameter, correoElectronicoVParameter, idEmpresaVParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> uspTablas(string nombreDeTabla)
        {
            var nombreDeTablaParameter = nombreDeTabla != null ?
                new ObjectParameter("NombreDeTabla", nombreDeTabla) :
                new ObjectParameter("NombreDeTabla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("uspTablas", nombreDeTablaParameter);
        }
    
        public virtual int usptblCompra(Nullable<int> idProovedor, Nullable<System.DateTime> fecha, Nullable<decimal> precioTotal, Nullable<int> idTipoPago, string idProductos)
        {
            var idProovedorParameter = idProovedor.HasValue ?
                new ObjectParameter("idProovedor", idProovedor) :
                new ObjectParameter("idProovedor", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var precioTotalParameter = precioTotal.HasValue ?
                new ObjectParameter("PrecioTotal", precioTotal) :
                new ObjectParameter("PrecioTotal", typeof(decimal));
    
            var idTipoPagoParameter = idTipoPago.HasValue ?
                new ObjectParameter("idTipoPago", idTipoPago) :
                new ObjectParameter("idTipoPago", typeof(int));
    
            var idProductosParameter = idProductos != null ?
                new ObjectParameter("idProductos", idProductos) :
                new ObjectParameter("idProductos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usptblCompra", idProovedorParameter, fechaParameter, precioTotalParameter, idTipoPagoParameter, idProductosParameter);
        }
    
        public virtual ObjectResult<usptblResultado_Result> usptblResultado(Nullable<int> idResultadoV, Nullable<int> idUsuarioV, string moduloV, string metodosV, Nullable<int> idEstatusV, string mensajeV, string mensajeDeSistemaV, Nullable<System.DateTime> fechaV)
        {
            var idResultadoVParameter = idResultadoV.HasValue ?
                new ObjectParameter("idResultadoV", idResultadoV) :
                new ObjectParameter("idResultadoV", typeof(int));
    
            var idUsuarioVParameter = idUsuarioV.HasValue ?
                new ObjectParameter("idUsuarioV", idUsuarioV) :
                new ObjectParameter("idUsuarioV", typeof(int));
    
            var moduloVParameter = moduloV != null ?
                new ObjectParameter("moduloV", moduloV) :
                new ObjectParameter("moduloV", typeof(string));
    
            var metodosVParameter = metodosV != null ?
                new ObjectParameter("metodosV", metodosV) :
                new ObjectParameter("metodosV", typeof(string));
    
            var idEstatusVParameter = idEstatusV.HasValue ?
                new ObjectParameter("idEstatusV", idEstatusV) :
                new ObjectParameter("idEstatusV", typeof(int));
    
            var mensajeVParameter = mensajeV != null ?
                new ObjectParameter("mensajeV", mensajeV) :
                new ObjectParameter("mensajeV", typeof(string));
    
            var mensajeDeSistemaVParameter = mensajeDeSistemaV != null ?
                new ObjectParameter("mensajeDeSistemaV", mensajeDeSistemaV) :
                new ObjectParameter("mensajeDeSistemaV", typeof(string));
    
            var fechaVParameter = fechaV.HasValue ?
                new ObjectParameter("fechaV", fechaV) :
                new ObjectParameter("fechaV", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usptblResultado_Result>("usptblResultado", idResultadoVParameter, idUsuarioVParameter, moduloVParameter, metodosVParameter, idEstatusVParameter, mensajeVParameter, mensajeDeSistemaVParameter, fechaVParameter);
        }
    
        public virtual int usptblTokenRecuperar(string tokenV, Nullable<int> idUsuarioV)
        {
            var tokenVParameter = tokenV != null ?
                new ObjectParameter("TokenV", tokenV) :
                new ObjectParameter("TokenV", typeof(string));
    
            var idUsuarioVParameter = idUsuarioV.HasValue ?
                new ObjectParameter("idUsuarioV", idUsuarioV) :
                new ObjectParameter("idUsuarioV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usptblTokenRecuperar", tokenVParameter, idUsuarioVParameter);
        }
    
        public virtual ObjectResult<uspTokenUsuarioN_Result> uspTokenUsuarioN(string pantalla, string token)
        {
            var pantallaParameter = pantalla != null ?
                new ObjectParameter("Pantalla", pantalla) :
                new ObjectParameter("Pantalla", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspTokenUsuarioN_Result>("uspTokenUsuarioN", pantallaParameter, tokenParameter);
        }
    
        public virtual int uspUEProducto(Nullable<int> idProducto, Nullable<int> cantidad)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUEProducto", idProductoParameter, cantidadParameter);
        }
    
        public virtual int uspUPDCodigo(Nullable<int> id, string codigo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUPDCodigo", idParameter, codigoParameter);
        }
    
        public virtual int uspUPDPago(Nullable<int> idVenta, Nullable<double> miPago)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            var miPagoParameter = miPago.HasValue ?
                new ObjectParameter("MiPago", miPago) :
                new ObjectParameter("MiPago", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUPDPago", idVentaParameter, miPagoParameter);
        }
    
        public virtual int uspUPDToken(Nullable<int> idUsuario, string token)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUPDToken", idUsuarioParameter, tokenParameter);
        }
    
        public virtual ObjectResult<uspUsuarios2_Result> uspUsuarios2(Nullable<int> idUsuario, string nombreV, string correoElectronicoV, string claveAccesoV, string telefono1V, string telefono2V, Nullable<int> idRol, Nullable<int> idEstatus, string tokenV)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var nombreVParameter = nombreV != null ?
                new ObjectParameter("NombreV", nombreV) :
                new ObjectParameter("NombreV", typeof(string));
    
            var correoElectronicoVParameter = correoElectronicoV != null ?
                new ObjectParameter("CorreoElectronicoV", correoElectronicoV) :
                new ObjectParameter("CorreoElectronicoV", typeof(string));
    
            var claveAccesoVParameter = claveAccesoV != null ?
                new ObjectParameter("ClaveAccesoV", claveAccesoV) :
                new ObjectParameter("ClaveAccesoV", typeof(string));
    
            var telefono1VParameter = telefono1V != null ?
                new ObjectParameter("Telefono1V", telefono1V) :
                new ObjectParameter("Telefono1V", typeof(string));
    
            var telefono2VParameter = telefono2V != null ?
                new ObjectParameter("Telefono2V", telefono2V) :
                new ObjectParameter("Telefono2V", typeof(string));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(int));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var tokenVParameter = tokenV != null ?
                new ObjectParameter("TokenV", tokenV) :
                new ObjectParameter("TokenV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspUsuarios2_Result>("uspUsuarios2", idUsuarioParameter, nombreVParameter, correoElectronicoVParameter, claveAccesoVParameter, telefono1VParameter, telefono2VParameter, idRolParameter, idEstatusParameter, tokenVParameter);
        }
    
        public virtual ObjectResult<uspVenta_Result> uspVenta(Nullable<int> idVenta, Nullable<System.DateTime> fecha, Nullable<decimal> importe, Nullable<int> idUsuario, Nullable<decimal> pago, Nullable<int> idTipoPago, string cliente, string movil)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var importeParameter = importe.HasValue ?
                new ObjectParameter("importe", importe) :
                new ObjectParameter("importe", typeof(decimal));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var pagoParameter = pago.HasValue ?
                new ObjectParameter("Pago", pago) :
                new ObjectParameter("Pago", typeof(decimal));
    
            var idTipoPagoParameter = idTipoPago.HasValue ?
                new ObjectParameter("idTipoPago", idTipoPago) :
                new ObjectParameter("idTipoPago", typeof(int));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var movilParameter = movil != null ?
                new ObjectParameter("Movil", movil) :
                new ObjectParameter("Movil", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspVenta_Result>("uspVenta", idVentaParameter, fechaParameter, importeParameter, idUsuarioParameter, pagoParameter, idTipoPagoParameter, clienteParameter, movilParameter);
        }
    
        public virtual int uspVentas(Nullable<int> idVentaV, Nullable<int> idClienteV, Nullable<int> idProductoV, Nullable<System.DateTime> fechaVentaV, Nullable<int> cantidadV, Nullable<decimal> precioV, Nullable<decimal> totalV, string metodoPagoV, string estadoVentaV)
        {
            var idVentaVParameter = idVentaV.HasValue ?
                new ObjectParameter("idVentaV", idVentaV) :
                new ObjectParameter("idVentaV", typeof(int));
    
            var idClienteVParameter = idClienteV.HasValue ?
                new ObjectParameter("idClienteV", idClienteV) :
                new ObjectParameter("idClienteV", typeof(int));
    
            var idProductoVParameter = idProductoV.HasValue ?
                new ObjectParameter("idProductoV", idProductoV) :
                new ObjectParameter("idProductoV", typeof(int));
    
            var fechaVentaVParameter = fechaVentaV.HasValue ?
                new ObjectParameter("FechaVentaV", fechaVentaV) :
                new ObjectParameter("FechaVentaV", typeof(System.DateTime));
    
            var cantidadVParameter = cantidadV.HasValue ?
                new ObjectParameter("CantidadV", cantidadV) :
                new ObjectParameter("CantidadV", typeof(int));
    
            var precioVParameter = precioV.HasValue ?
                new ObjectParameter("PrecioV", precioV) :
                new ObjectParameter("PrecioV", typeof(decimal));
    
            var totalVParameter = totalV.HasValue ?
                new ObjectParameter("TotalV", totalV) :
                new ObjectParameter("TotalV", typeof(decimal));
    
            var metodoPagoVParameter = metodoPagoV != null ?
                new ObjectParameter("MetodoPagoV", metodoPagoV) :
                new ObjectParameter("MetodoPagoV", typeof(string));
    
            var estadoVentaVParameter = estadoVentaV != null ?
                new ObjectParameter("EstadoVentaV", estadoVentaV) :
                new ObjectParameter("EstadoVentaV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspVentas", idVentaVParameter, idClienteVParameter, idProductoVParameter, fechaVentaVParameter, cantidadVParameter, precioVParameter, totalVParameter, metodoPagoVParameter, estadoVentaVParameter);
        }
    }
}
