//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCatalogo
    {
        public tblCatalogo()
        {
            this.tblCampo = new HashSet<tblCampo>();
            this.tblPantalla = new HashSet<tblPantalla>();
            this.tblPermisoPorPantalla = new HashSet<tblPermisoPorPantalla>();
            this.tblProducto = new HashSet<tblProducto>();
            this.tblProducto1 = new HashSet<tblProducto>();
            this.tblProducto2 = new HashSet<tblProducto>();
            this.tblProveedor = new HashSet<tblProveedor>();
            this.tblUsuario = new HashSet<tblUsuario>();
            this.tblVenta = new HashSet<tblVenta>();
            this.tblVenta1 = new HashSet<tblVenta>();
        }
    
        public int Id_Catalogo { get; set; }
        public Nullable<int> IdOrigen { get; set; }
        public int Orden { get; set; }
        public string Catalogo { get; set; }
        public string Valor { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ValorDefault { get; set; }
    
        public virtual ICollection<tblCampo> tblCampo { get; set; }
        public virtual ICollection<tblPantalla> tblPantalla { get; set; }
        public virtual ICollection<tblPermisoPorPantalla> tblPermisoPorPantalla { get; set; }
        public virtual ICollection<tblProducto> tblProducto { get; set; }
        public virtual ICollection<tblProducto> tblProducto1 { get; set; }
        public virtual ICollection<tblProducto> tblProducto2 { get; set; }
        public virtual ICollection<tblProveedor> tblProveedor { get; set; }
        public virtual ICollection<tblUsuario> tblUsuario { get; set; }
        public virtual ICollection<tblVenta> tblVenta { get; set; }
        public virtual ICollection<tblVenta> tblVenta1 { get; set; }
    }
}
