//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetalleVenta
    {
        public int idDetalleVenta { get; set; }
        public int idVenta { get; set; }
        public int idProducto { get; set; }
        public double Cantidad { get; set; }
        public double Importe { get; set; }
    
        public virtual tblProducto tblProducto { get; set; }
        public virtual tblVenta tblVenta { get; set; }
    }
}
