//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermisoPorPantalla
    {
        public int idPermisoPorPantalla { get; set; }
        public int idPantalla { get; set; }
        public int idPermiso { get; set; }
    
        public virtual tblCatalogo tblCatalogo { get; set; }
        public virtual tblPantalla tblPantalla { get; set; }
    }
}
