//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProveedor
    {
        public int idProveedor { get; set; }
        public string razonSocial { get; set; }
        public string direccion { get; set; }
        public string contacto { get; set; }
        public decimal telefonoContacto { get; set; }
        public string correoElectronico { get; set; }
        public int idEmpresa { get; set; }
    
        public virtual tblCatalogo tblCatalogo { get; set; }
    }
}
