//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPantalla
    {
        public tblPantalla()
        {
            this.tblPermisoPorPantalla = new HashSet<tblPermisoPorPantalla>();
        }
    
        public int idPantalla { get; set; }
        public Nullable<int> idOrigen { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Pantalla { get; set; }
        public string url { get; set; }
        public string Clase { get; set; }
        public string ToolTip { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> idEstatus { get; set; }
        public string MsgGuardar { get; set; }
        public string MsgEliminar { get; set; }
        public string PreguntaEliminar { get; set; }
        public string urlMovil { get; set; }
    
        public virtual tblCatalogo tblCatalogo { get; set; }
        public virtual ICollection<tblPermisoPorPantalla> tblPermisoPorPantalla { get; set; }
    }
}
