//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducto
    {
        public tblProducto()
        {
            this.tblDetalleVenta = new HashSet<tblDetalleVenta>();
        }
    
        public int idProducto { get; set; }
        public string Productos { get; set; }
        public string Descripcion { get; set; }
        public int PiezasXcaja { get; set; }
        public Nullable<double> CostoXCaja { get; set; }
        public int idUnidad { get; set; }
        public Nullable<double> PrecioPublico { get; set; }
        public Nullable<int> PiezasXPaquete { get; set; }
        public Nullable<int> CantidadMinima { get; set; }
        public Nullable<int> Existencia { get; set; }
        public string Codigo { get; set; }
        public int idCategoria { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> idEstatus { get; set; }
    
        public virtual tblCatalogo tblCatalogo { get; set; }
        public virtual tblCatalogo tblCatalogo1 { get; set; }
        public virtual tblCatalogo tblCatalogo2 { get; set; }
        public virtual ICollection<tblDetalleVenta> tblDetalleVenta { get; set; }
    }
}
