//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResultado
    {
        public int idResultado { get; set; }
        public int idUsuario { get; set; }
        public string modulo { get; set; }
        public string metodos { get; set; }
        public int idEstatus { get; set; }
        public string mensaje { get; set; }
        public string mensajeDeSistema { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
