//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        public tblUsuario()
        {
            this.tblVenta = new HashSet<tblVenta>();
            this.tblVentas = new HashSet<tblVentas>();
        }
    
        public int idUsuario { get; set; }
        public string Nombre { get; set; }
        public string CorreoElectronico { get; set; }
        public string ClaveAcceso { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public int idRol { get; set; }
        public int idEstatus { get; set; }
        public string Token { get; set; }
    
        public virtual tblCatalogo tblCatalogo { get; set; }
        public virtual ICollection<tblVenta> tblVenta { get; set; }
        public virtual ICollection<tblVentas> tblVentas { get; set; }
    }
}
