//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVenta
    {
        public tblVenta()
        {
            this.tblDetalleVenta = new HashSet<tblDetalleVenta>();
        }
    
        public int idVenta { get; set; }
        public int idCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
        public int idUsuario { get; set; }
        public Nullable<decimal> Pago { get; set; }
        public int idTipoPago { get; set; }
    
        public virtual tblCatalogo tblCatalogo { get; set; }
        public virtual tblCatalogo tblCatalogo1 { get; set; }
        public virtual ICollection<tblDetalleVenta> tblDetalleVenta { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
