//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVentas
    {
        public int idVenta { get; set; }
        public int idCliente { get; set; }
        public int idProducto { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Total { get; set; }
        public string MetodoPago { get; set; }
        public string EstadoVenta { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
