//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProducto
    {
        public string Productos { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Codigo { get; set; }
        public string Unidad { get; set; }
        public string Descripcion { get; set; }
        public int PiezasXcaja { get; set; }
        public Nullable<double> CostoXCaja { get; set; }
        public int idUnidad { get; set; }
        public Nullable<int> CantidadMinima { get; set; }
        public Nullable<int> Existencia { get; set; }
        public int idCategoria { get; set; }
        public Nullable<int> PiezasXPaquete { get; set; }
        public int idProducto { get; set; }
        public string Categoria { get; set; }
        public string Imagen { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> idEstatus { get; set; }
    }
}
