//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProveedor
    {
        public int idProveedor { get; set; }
        public string Empresa { get; set; }
        public string NombreContacto { get; set; }
        public decimal telefonoContacto { get; set; }
        public string Empresa_es { get; set; }
    }
}
