//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTablas
    {
        public int idCampo { get; set; }
        public int idTabla { get; set; }
        public string NombreTabla { get; set; }
        public string Campo { get; set; }
        public string Tipo { get; set; }
        public string Etiqueta { get; set; }
        public Nullable<int> Longitud { get; set; }
        public string Descripcion { get; set; }
        public string Validacion { get; set; }
        public int Orden { get; set; }
        public string Clase { get; set; }
        public string Catalogo { get; set; }
        public Nullable<int> EsNulo { get; set; }
        public int No_Columna { get; set; }
    }
}
