//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtblCompraDetallada
    {
        public int idCompra { get; set; }
        public int idProveedor { get; set; }
        public string Proveedor { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
        public int idTipoPago { get; set; }
        public string TipoPago { get; set; }
        public string DiccionarioOriginal { get; set; }
        public string ProductosConCantidad { get; set; }
    }
}
