//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVenta
    {
        public int idVenta { get; set; }
        public int idCliente { get; set; }
        public int idUsuario { get; set; }
        public int idTipoPago { get; set; }
        public string Cliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
        public string Vendio { get; set; }
        public Nullable<decimal> Pago { get; set; }
        public string TipodePago { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Estatus { get; set; }
        public string Movil { get; set; }
    }
}
